// ==UserScript==
// @name         estim-camming bridge (__SITE__)
// @namespace    estim-camming
// @version      3
// @description  Forwards tips on this page to estim-camming on this computer.
// __MATCH_LINES__
// @grant        GM_xmlhttpRequest
// @grant        unsafeWindow
// @sandbox      JavaScript
// @connect      127.0.0.1
// @run-at       document-start
// @noframes
// ==/UserScript==

// Generated by `estim-camming userscript`. Regenerate it after changing the
// platform options in config.toml. It contains your bridge token, so don't share it.
//
// websocket mode: a hook in the page observes the messages of the page's own
//   WebSocket (the chat connection); frames that may contain tips are sent to
//   the app. The app finds the tips
//   in the structured data, so chat text can't fake a tip.
// dom mode: every element matching tipSelector that appears after page load
//   is sent (as text) to the app, which parses it with tip_pattern. With an
//   empty tipSelector this is DISCOVERY MODE: nothing is sent, and new page
//   elements are logged to the browser console to help find the selector.

(function () {
  "use strict";

  const CONFIG = __CONFIG__;
  const BASE = `http://127.0.0.1:${CONFIG.port}`;
  const startedAt = Date.now();
  const log = (...args) => console.log("[estim-bridge]", ...args);
  if (CONFIG.debug) log("userscript started", CONFIG.mode, "mode on", location.href);

  // -- helpers ----------------------------------------------------------------
  function inRoom() {
    if (!CONFIG.room) return true;
    const first = location.pathname.split("/")[1] || "";
    return first.toLowerCase() === CONFIG.room.toLowerCase();
  }

  function warmingUp() {
    return Date.now() - startedAt < CONFIG.ignoreFirstSeconds * 1000;
  }

  function whenBody(fn) {
    if (document.body) fn();
    else document.addEventListener("DOMContentLoaded", fn, { once: true });
  }

  // -- status badge -----------------------------------------------------------
  let badge = null;
  let status = { ok: false, detail: "starting…" };
  let lastTip = "";
  let extraBadge = () => "";

  function renderBadge() {
    if (!badge) return;
    badge.style.background = status.ok ? "#2f7d45" : "#b3261e";
    const room = inRoom() ? "" : " · not your room, ignoring";
    badge.textContent =
      `estim bridge (${CONFIG.mode}): ${status.detail}${room}${extraBadge()}` +
      (lastTip ? ` · last: ${lastTip}` : "");
  }

  function setStatus(ok, detail) {
    status = { ok, detail };
    renderBadge();
  }

  whenBody(() => {
    badge = document.createElement("div");
    badge.style.cssText =
      "position:fixed;left:8px;bottom:8px;z-index:2147483647;padding:4px 8px;" +
      "border-radius:6px;font:12px/1.3 system-ui,sans-serif;color:#fff;" +
      "background:#555;opacity:.85;pointer-events:none;max-width:360px";
    document.body.appendChild(badge);
    renderBadge();
  });

  // -- communication with the app --------------------------------------------
  function post(path, body, done) {
    GM_xmlhttpRequest({
      method: "POST",
      url: BASE + path,
      headers: { "Content-Type": "application/json", "X-Bridge-Token": CONFIG.token },
      data: JSON.stringify(body),
      timeout: 3000,
      onload: (res) => {
        let data = null;
        try { data = JSON.parse(res.responseText); } catch (e) { /* not JSON */ }
        done(res.status === 200, res.status, data);
      },
      onerror: () => done(false, 0, null),
      ontimeout: () => done(false, 0, null),
    });
  }

  let hookProblem = "";

  function ping() {
    post("/ping", {}, (ok, status, data) => {
      if (!ok) {
        setStatus(false, status === 401 ? "wrong token, regenerate the userscript"
          : status === 404 ? "mode mismatch, regenerate the userscript"
          : "app not reachable, is estim-camming running?");
      } else if (data && data.mode && data.mode !== CONFIG.mode) {
        setStatus(false, "mode mismatch, regenerate the userscript");
      } else if (hookProblem) {
        setStatus(false, hookProblem);
      } else if (CONFIG.mode === "dom" && !CONFIG.tipSelector) {
        setStatus(true, "connected (discovery mode)");
      } else {
        setStatus(true, "connected");
      }
    });
  }

  function reportSend(ok, httpStatus, data) {
    if (!ok) { setStatus(false, `send failed (HTTP ${httpStatus || "-"})`); return; }
    if (data && Array.isArray(data.tips) && data.tips.length) lastTip = data.tips.map((n) => `${n} tk`).join(", ");
    if (data && data.matched) lastTip = `${data.tokens} tk`;
    setStatus(true, data && data.matched === false ? "tip text not recognised (see app log)" : "connected");
  }

  ping();
  setInterval(ping, 10000);

  // -- websocket mode ---------------------------------------------------------
  // The hook wraps the getter of MessageEvent.data in the page: every time the
  // site reads a WebSocket message, we see it too. Unlike replacing the
  // WebSocket class this also works for connections the page opened before
  // this script ran. It only observes; the page gets the same data.
  //
  // Two ways to install it in the page:
  //  - direct: through Tampermonkey's unsafeWindow (@sandbox JavaScript). Not
  //    affected by the site's Content Security Policy.
  //  - script: a <script> element (fallback, blocked by a strict CSP). It
  //    passes data back via postMessage with a random per-page nonce.
  function installHook(w, deliver) {
    if (w.__estimBridgeHook) return false;
    const proto = w.MessageEvent && w.MessageEvent.prototype;
    const desc = proto && Object.getOwnPropertyDescriptor(proto, "data");
    if (!desc || typeof desc.get !== "function") return false;
    const NativeWebSocket = w.WebSocket;
    const originalGet = desc.get;
    const seen = new WeakSet();
    Object.defineProperty(proto, "data", {
      configurable: true,
      enumerable: desc.enumerable,
      get: function () {
        const value = originalGet.call(this);
        try {
          const target = this.target;
          if (target instanceof NativeWebSocket && !seen.has(this)) {
            seen.add(this);
            deliver(String(target.url), value);
          }
        } catch (e) { /* never break the page */ }
        return value;
      },
    });
    w.__estimBridgeHook = true;
    return true;
  }

  if (CONFIG.mode === "websocket") {
    let framesSeen = 0;
    let binarySeen = 0;
    let directWorks = false;
    const socketsSeen = new Set();

    function onData(url, data, via) {
      if (via === "direct") directWorks = true;
      else if (directWorks) return; // both hooks active: use one
      if (!socketsSeen.has(url)) {
        socketsSeen.add(url);
        log(`listening to ${url} (${via} hook)`);
      }
      if (typeof data !== "string") {
        binarySeen++;
        if (CONFIG.debug) log("binary frame from", url, data && data.binary ? data.binary : String(data));
        return;
      }
      framesSeen++;
      const candidate = data.indexOf('"amount"') !== -1;
      // debug: also forward anything mentioning "tip", so the app log shows
      // frames the parser doesn't recognise (the parser only accepts real tips).
      const mentionsTip = CONFIG.debug && !candidate && /tip/i.test(data);
      if (CONFIG.debug) {
        const label = candidate ? "TIP CANDIDATE from" : mentionsTip ? "POSSIBLE TIP from" : "frame from";
        log(label, url, data.slice(0, 500));
      }
      if (!candidate && !mentionsTip) return;
      if (!inRoom() || warmingUp()) {
        if (CONFIG.debug) log(`not sent: ${inRoom() ? "within ignore_first_seconds" : "not your room"}`);
        return;
      }
      post("/frame", { frame: data }, reportSend);
    }

    extraBadge = () => ` · frames: ${framesSeen}` + (binarySeen ? `, binary: ${binarySeen}` : "");
    setInterval(renderBadge, 1000);

    // 1. direct hook
    let direct = false;
    try {
      if (typeof unsafeWindow !== "undefined") {
        direct = installHook(unsafeWindow, (url, data) => onData(url, data, "direct"));
      }
    } catch (e) {
      log("direct hook failed:", String(e));
    }

    // 2. <script> fallback (does nothing if the direct hook already runs in the page)
    const bytes = new Uint8Array(16);
    crypto.getRandomValues(bytes);
    const nonce = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
    const script = document.createElement("script");
    script.textContent = `(() => {
      const NONCE = ${JSON.stringify(nonce)};
      const installed = (${installHook.toString()})(window, (url, data) => {
        const msg = { estimBridge: NONCE, url };
        if (typeof data === "string") msg.frame = data;
        else msg.binary = Object.prototype.toString.call(data);
        window.postMessage(msg, window.location.origin);
      });
      if (installed) document.documentElement.setAttribute("data-estim-bridge", "hooked");
    })();`;
    (document.head || document.documentElement).appendChild(script);
    script.remove();
    const scripted = document.documentElement.getAttribute("data-estim-bridge") === "hooked";

    // Not `event.source === window`: with @grant, Tampermonkey's `window` is a
    // sandbox proxy, never the page window that posted the message. The
    // per-page nonce is the real check; the origin check rejects iframes.
    window.addEventListener("message", (event) => {
      const msg = event.data;
      if (event.origin !== location.origin || !msg || msg.estimBridge !== nonce) return;
      onData(msg.url, typeof msg.frame === "string" ? msg.frame : { binary: msg.binary }, "script");
    });

    if (CONFIG.debug) log(`hook installed: direct=${direct}, script=${scripted}`);
    if (!direct && !scripted) {
      hookProblem = "could not hook the page, try mode = \"dom\"";
      log(hookProblem);
      setStatus(false, hookProblem);
    }
    return;
  }

  // -- dom mode: discovery ----------------------------------------------------
  function describe(el) {
    const parts = [];
    for (let e = el; e && e !== document.body && parts.length < 4; e = e.parentElement) {
      const cls = [...e.classList].map((c) => "." + CSS.escape(c)).join("");
      parts.unshift(e.tagName.toLowerCase() + cls);
    }
    return parts.join(" > ");
  }

  if (!CONFIG.tipSelector) {
    whenBody(() => {
      log("discovery mode: logging new elements that contain numbers");
      new MutationObserver((mutations) => {
        for (const m of mutations) {
          for (const node of m.addedNodes) {
            if (!(node instanceof Element)) continue;
            const text = node.textContent.replace(/\s+/g, " ").trim();
            if (text && text.length < 200 && /\d/.test(text)) {
              log(JSON.stringify(text), "\n   ", describe(node));
            }
          }
        }
      }).observe(document.body, { childList: true, subtree: true });
    });
    return;
  }

  // -- dom mode: forwarding ---------------------------------------------------
  const session = Math.random().toString(36).slice(2, 10);
  const seen = new WeakSet();
  let counter = 0;

  function send(el) {
    const text = el.textContent.replace(/\s+/g, " ").trim();
    if (!text) return;
    if (CONFIG.debug) log("tip element", JSON.stringify(text));
    post("/tip", { id: `${session}-${++counter}`, text }, reportSend);
  }

  function handle(el) {
    if (seen.has(el)) return;
    seen.add(el);
    if (!inRoom() || warmingUp()) return;
    // Frameworks often insert an element first and fill in its text afterwards.
    setTimeout(() => send(el), 250);
  }

  function scan(node) {
    if (!(node instanceof Element)) return;
    if (node.matches(CONFIG.tipSelector)) handle(node);
    node.querySelectorAll(CONFIG.tipSelector).forEach(handle);
  }

  whenBody(() => {
    try {
      document.querySelector(CONFIG.tipSelector);
    } catch (e) {
      hookProblem = "invalid tip_selector, fix it in config.toml";
      setStatus(false, hookProblem);
      return;
    }
    // Tips already on the page (chat history) are never sent.
    document.querySelectorAll(CONFIG.tipSelector).forEach((el) => seen.add(el));
    new MutationObserver((mutations) => {
      for (const m of mutations) m.addedNodes.forEach(scan);
    }).observe(document.body, { childList: true, subtree: true });
  });
})();
