"""Browser bridge: receive tips from a userscript running on the site's own page.

For sites without an official tip API. A userscript (generated by
``estim-camming userscript``) runs in the performer's logged-in browser tab and
POSTs to this platform on 127.0.0.1. Two modes:

* ``websocket``: the userscript hooks the page's own WebSocket and forwards raw
  frames; a site-specific :meth:`BridgePlatform.parse_frame` extracts tips from
  the structured data. Chat text cannot fake a tip. Needs a parser (Stripchat).
* ``dom``: the userscript forwards the text of elements matching
  ``tip_selector``; it is parsed with the ``tip_pattern`` regex. Works for any
  site, but relies on the selector matching *only* tip notifications.

See ``docs/design/platforms.md``.
"""

from __future__ import annotations

import asyncio
import hmac
import json
import logging
import re
from collections.abc import AsyncIterator
from importlib.resources import files
from typing import Literal

from aiohttp import web
from pydantic import Field, SecretStr, field_validator

from estim_camming.events import TipEvent
from estim_camming.platforms.base import Platform
from estim_camming.plugins import PLATFORMS, PluginOptions

log = logging.getLogger(__name__)

USERSCRIPT_TEMPLATE = files("estim_camming.platforms") / "bridge.user.js"
_MAX_TEXT = 500
_MAX_FRAME = 200_000
_MAX_SEEN = 10_000


class BridgeOptions(PluginOptions):
    site: str = Field("bridge", description="Platform name shown in logs and the overlay.")
    mode: Literal["dom"] = Field(
        "dom", description="'dom': read tip elements from the page (see tip_selector)."
    )
    port: int = Field(8766, ge=1024, le=65535, description="Local port the userscript sends to.")
    token: SecretStr = Field(
        min_length=16,
        description="Shared secret between the userscript and the app (16+ characters).",
    )
    match: list[str] = Field(
        default_factory=list, description="Userscript @match URL patterns (pages to run on)."
    )
    room: str = Field(
        "",
        description="Only forward tips on pages whose first path segment is this "
        "(your username). Empty: any page.",
    )
    tip_selector: str = Field(
        "",
        description="dom mode: CSS selector for tip-notification elements. Empty: discovery mode.",
    )
    tip_pattern: str = Field(
        r"^\s*(?P<user>\S+)\s+tipped\s+(?P<amount>\d[\d,]*)(?:\s*(?:tk|tokens?)\b)?",
        description="dom mode: regex with named groups 'amount' and optionally 'user'.",
    )
    ignore_first_seconds: float = Field(
        5.0, ge=0, description="Ignore tips shown right after page load (chat history)."
    )
    debug: bool = Field(False, description="Log page data to the browser console.")

    @field_validator("token")
    @classmethod
    def _check_token(cls, value: SecretStr) -> SecretStr:
        if value.get_secret_value().upper().startswith("CHANGE-ME"):
            raise ValueError("replace the example token with your own long random string")
        return value

    @field_validator("tip_pattern")
    @classmethod
    def _check_pattern(cls, value: str) -> str:
        try:
            compiled = re.compile(value)
        except re.error as exc:
            raise ValueError(f"invalid regular expression: {exc}") from exc
        if "amount" not in compiled.groupindex:
            raise ValueError("tip_pattern needs a named group 'amount', e.g. (?P<amount>\\d+)")
        return value


@PLATFORMS.register("bridge")
class BridgePlatform(Platform):
    """Tips forwarded by a browser userscript (for sites without a tip API)."""

    Options = BridgeOptions

    def __init__(self, options=None) -> None:
        super().__init__(options)
        self._pattern = re.compile(self.options.tip_pattern)
        self._seen: set[str] = set()
        self._contacted = False

    @property
    def site(self) -> str:
        return self.options.site

    def describe(self) -> str:
        return f"{self.site} (browser bridge :{self.options.port})"

    # -- parsing -----------------------------------------------------------

    def parse_text(self, text: str) -> TipEvent | None:
        """dom mode: turn the text of a tip element into a TipEvent, or None."""
        match = self._pattern.search(text)
        if match is None:
            return None
        try:
            tokens = int(match.group("amount").replace(",", ""))
        except ValueError:
            return None
        if tokens <= 0:
            return None
        user = (match.groupdict().get("user") or "").strip() or "unknown"
        anonymous = user.lower() in ("anonymous", "anon")
        return TipEvent(
            platform=self.site,
            username="anonymous" if anonymous else user,
            tokens=tokens,
            message=text[match.end() :].strip(" :-")[:200],
            anonymous=anonymous,
        )

    def parse_frame(self, frame: str) -> list[TipEvent]:
        """websocket mode: extract tips from one WebSocket frame of the site.

        Site-specific; subclasses that allow ``mode = "websocket"`` override it.
        Returned events must have a stable ``event_id`` for de-duplication.
        """
        raise NotImplementedError

    def _is_new(self, event_id: str) -> bool:
        if event_id in self._seen:
            return False
        if len(self._seen) >= _MAX_SEEN:
            self._seen.clear()
        self._seen.add(event_id)
        return True

    # -- userscript --------------------------------------------------------

    def userscript(self) -> str:
        """The userscript for this platform, with its settings filled in."""
        config = {
            "site": self.site,
            "mode": self.options.mode,
            "port": self.options.port,
            "token": self.options.token.get_secret_value(),
            "room": self.options.room,
            "tipSelector": self.options.tip_selector,
            "ignoreFirstSeconds": self.options.ignore_first_seconds,
            "debug": self.options.debug,
        }
        match_lines = "\n".join(f"// @match        {m}" for m in self.options.match)
        return (
            USERSCRIPT_TEMPLATE.read_text()
            .replace("__SITE__", self.site)
            .replace("// __MATCH_LINES__", match_lines)
            .replace("__CONFIG__", json.dumps(config))
        )

    # -- server ------------------------------------------------------------

    def make_app(self, queue: asyncio.Queue[TipEvent]) -> web.Application:
        token = self.options.token.get_secret_value().encode()

        @web.middleware
        async def auth(request: web.Request, handler):
            # A JSON content type forces a CORS preflight for requests from web
            # pages (which we never answer), and the token must match. A page
            # that could forge tips could trigger the device.
            if request.content_type != "application/json":
                raise web.HTTPUnsupportedMediaType(text="Content-Type must be application/json")
            given = request.headers.get("X-Bridge-Token", "").encode()
            if not hmac.compare_digest(given, token):
                raise web.HTTPUnauthorized(text="invalid bridge token")
            if not self._contacted:
                self._contacted = True
                log.info("%s: userscript connected", self.describe())
            return await handler(request)

        async def json_body(request: web.Request) -> dict:
            try:
                body = await request.json()
            except (json.JSONDecodeError, UnicodeDecodeError):
                raise web.HTTPBadRequest(text="invalid JSON") from None
            if not isinstance(body, dict):
                raise web.HTTPBadRequest(text="expected a JSON object")
            return body

        async def ping(request: web.Request) -> web.Response:
            return web.json_response({"ok": True, "mode": self.options.mode})

        async def tip(request: web.Request) -> web.Response:
            body = await json_body(request)
            if "id" not in body or "text" not in body:
                raise web.HTTPBadRequest(text="expected {'id': str, 'text': str}")
            if not self._is_new(str(body["id"])[:100]):
                return web.json_response({"ok": True, "duplicate": True})
            text = str(body["text"])[:_MAX_TEXT]
            event = self.parse_text(text)
            if event is None:
                log.warning("%s: tip element did not match tip_pattern: %r", self.site, text)
                return web.json_response({"ok": True, "matched": False})
            await queue.put(event)
            return web.json_response({"ok": True, "matched": True, "tokens": event.tokens})

        async def frame(request: web.Request) -> web.Response:
            body = await json_body(request)
            if not isinstance(body.get("frame"), str) or len(body["frame"]) > _MAX_FRAME:
                raise web.HTTPBadRequest(text="expected {'frame': str}")
            parsed = self.parse_frame(body["frame"])
            if not parsed:
                log.info("%s: frame without a recognised tip: %.2000s", self.site, body["frame"])
            tips = [t for t in parsed if self._is_new(t.event_id)]
            for event in tips:
                await queue.put(event)
            return web.json_response({"ok": True, "tips": [t.tokens for t in tips]})

        routes = [web.post("/ping", ping)]
        if self.options.mode == "websocket":
            routes.append(web.post("/frame", frame))
        else:
            routes.append(web.post("/tip", tip))
        app = web.Application(middlewares=[auth], client_max_size=_MAX_FRAME * 2)
        app.add_routes(routes)
        return app

    async def stream(self) -> AsyncIterator[TipEvent]:
        queue: asyncio.Queue[TipEvent] = asyncio.Queue()
        runner = web.AppRunner(self.make_app(queue), access_log=None)
        await runner.setup()
        try:
            await web.TCPSite(runner, "127.0.0.1", self.options.port).start()
            log.info("%s: waiting for the userscript (%s mode)", self.describe(), self.options.mode)
            if self.options.mode == "dom" and not self.options.tip_selector:
                log.warning(
                    "%s: tip_selector is empty - the userscript runs in discovery mode "
                    "and forwards nothing (see the user guide)",
                    self.site,
                )
            while True:
                yield await queue.get()
        finally:
            await runner.cleanup()
